# this is a resource for app-of-apps pattern
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-staging # the environment name
  namespace: argo 
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec: 
  project: default
  source:
    repoURL: https://github.com/nurembergwitch/argodemo.git
    targetRevision: HEAD # points to the main branch's latest commit
    path: environments/staging/apps # tracked path is now the one containing all the apps, path in the github repo where Application crds are
  destination: 
    server: https://kubernetes.default.svc
    #namespace: some-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true # if the deployment has an unknown field, it will be rejected
      - CreateNamespace=true # like helm
      - PrunePropagationPolicy=foreground
      - PruneLast=true