---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shitchat
  namespace: chat
spec:
  selector:
    matchLabels:
      app: shitchat #must match service.spec.selector.app
  template:
    metadata:
      labels:
        app: shitchat #pod label
    spec:
      containers:
      - name: shitchat
        image: dirt1992/shitchat:latest
        imagePullPolicy: IfNotPresent
        resources: {}
        ports:
        - containerPort: 3000 # the corresponding service targets this port
        volumeMounts:
        - name: madsu-conf # mounting the configMap inside the container
          mountPath: /madsu
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: madsu-conf # mounting the configMap created with shitchat-env.yaml in the pod
        configMap:
          name: shitchat-env
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: chat
spec:
  type: NodePort # doesn't work w ClusterIP. Apparently NodePort is what works w Ingress now. Proof in ingress docs.
  selector:
    app: shitchat # must match deployment.spec.selector.matchLabels.app
  ports:
  - port: 80 # service port
    targetPort: 3000 # deployment port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-ingress
  namespace: chat
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  labels:
    name: chat-ingress
spec:
  ingressClassName: nginx # https://kubernetes.github.io/ingress-nginx/user-guide/basic-usage/
  rules:
  - host: madsuchat.com
    http:
      paths:
      - path: / # this path is serviced by the service chat-service on port 80
        pathType: Prefix
        backend:
          service:
            name: chat-service
            port:
              number: 80
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/persistentvolume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shitchat-pvc
  namespace: chat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeName: local-storage
  