# this is the patch to apply. Copy the header of whatever you're overriding, the override in spec
# include it in kustomization.aml with patchesStrategyMerge tag
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp
spec:
  replicas: 2