apiVersion: v1
kind: Service
metadata:
  name: pgpool-svc
  namespace: postgres
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - #name: postgresql
      port: 5445
      targetPort: 5432
      protocol: TCP
  selector:
    app: pgpool