# this is a resource for app-of-apps pattern
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-staging 
  namespace: argo 
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec: 
  project: default
  source:
    repoURL: https://github.com/nurembergwitch/argodemo-kustomize.git
    targetRevision: HEAD 
    path: environments/dev/myapp # the path to the final kustomization resource, but since the whole dir is tracked, the base is pointed at
  destination: 
    server: https://kubernetes.default.svc
    #namespace: some-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true # if the deployment has an unknown field, it will be rejected
      - CreateNamespace=true # like helm
      - PrunePropagationPolicy=foreground
      - PruneLast=true