apiVersion: v1
kind: Secret
metadata:
  name: git-key
  namespace: argo
  labels: 
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:nurembergwitch/argodemo-private.git # same priv repo as in the Application resource
  sshPrivateKey: |
    --------- BEGIN OPENSSH PRIVATE KEY ---------
    ur key here, the one you generated to paste its public part to github
    -------- end sjkdsds --------
  insecure: "false"
  enableLfs: "true"
