apiVersion: v1
kind: Service
metadata:
  name: mywebapp
  namespace: default
  # labels: # also unnecessary
  #   app: mykustomapp
spec:
  # selector:
  #   app: mykustomapp # technically this is unnecessary bc kustomization handles it
  ports:
  - port: 80
    protocol: TCP
    name: flask
    targetPort: 80
  type: LoadBalancer

