# for a helm chart
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argo 
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec: 
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/metrics-server # helm repo of the deployed chart
    targetRevision: 3.11.0 # chart version
    chart: metrics-server # name of the chart
    helm:
      version: v3 # the latest
      releaseName: my-metrics
      passCredentials: false # if the chart is open to anyone
      parameters: # the first way of overriding values
        - name: "image.tag"
          value: v0.6.2
      values: | # the 2nd way to override values
        defaultArgs:
        - --cert-dir=/tmp
        - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostnmae
        - --kubelet-use-node-status-port
        - --metric-resolution=15s
        - --kubelet-insecure-tls
  destination: 
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true 
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true