# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: wp-configmap
#   namespace: wp2
# data:
#   wordpress_db_host: wordpress-mysql # the name of mysql service
#   wordpress_db_user: wordpress

# moved to kustomization.yaml